/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposIndexRouteImport } from './routes/repos/index'
import { Route as ReposRepoIdRouteImport } from './routes/repos/$repoId'
import { Route as ReposRepoIdIndexRouteImport } from './routes/repos/$repoId/index'
import { Route as ReposRepoIdAnalysisRouteImport } from './routes/repos/$repoId/analysis'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRepoIdRoute = ReposRepoIdRouteImport.update({
  id: '/repos/$repoId',
  path: '/repos/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRepoIdIndexRoute = ReposRepoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReposRepoIdRoute,
} as any)
const ReposRepoIdAnalysisRoute = ReposRepoIdAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => ReposRepoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/settings': typeof SettingsRoute
  '/repos/$repoId': typeof ReposRepoIdRouteWithChildren
  '/repos/': typeof ReposIndexRoute
  '/repos/$repoId/analysis': typeof ReposRepoIdAnalysisRoute
  '/repos/$repoId/': typeof ReposRepoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/settings': typeof SettingsRoute
  '/repos': typeof ReposIndexRoute
  '/repos/$repoId/analysis': typeof ReposRepoIdAnalysisRoute
  '/repos/$repoId': typeof ReposRepoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/settings': typeof SettingsRoute
  '/repos/$repoId': typeof ReposRepoIdRouteWithChildren
  '/repos/': typeof ReposIndexRoute
  '/repos/$repoId/analysis': typeof ReposRepoIdAnalysisRoute
  '/repos/$repoId/': typeof ReposRepoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/settings'
    | '/repos/$repoId'
    | '/repos/'
    | '/repos/$repoId/analysis'
    | '/repos/$repoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/settings'
    | '/repos'
    | '/repos/$repoId/analysis'
    | '/repos/$repoId'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/settings'
    | '/repos/$repoId'
    | '/repos/'
    | '/repos/$repoId/analysis'
    | '/repos/$repoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  SettingsRoute: typeof SettingsRoute
  ReposRepoIdRoute: typeof ReposRepoIdRouteWithChildren
  ReposIndexRoute: typeof ReposIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/': {
      id: '/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$repoId': {
      id: '/repos/$repoId'
      path: '/repos/$repoId'
      fullPath: '/repos/$repoId'
      preLoaderRoute: typeof ReposRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$repoId/': {
      id: '/repos/$repoId/'
      path: '/'
      fullPath: '/repos/$repoId/'
      preLoaderRoute: typeof ReposRepoIdIndexRouteImport
      parentRoute: typeof ReposRepoIdRoute
    }
    '/repos/$repoId/analysis': {
      id: '/repos/$repoId/analysis'
      path: '/analysis'
      fullPath: '/repos/$repoId/analysis'
      preLoaderRoute: typeof ReposRepoIdAnalysisRouteImport
      parentRoute: typeof ReposRepoIdRoute
    }
  }
}

interface ReposRepoIdRouteChildren {
  ReposRepoIdAnalysisRoute: typeof ReposRepoIdAnalysisRoute
  ReposRepoIdIndexRoute: typeof ReposRepoIdIndexRoute
}

const ReposRepoIdRouteChildren: ReposRepoIdRouteChildren = {
  ReposRepoIdAnalysisRoute: ReposRepoIdAnalysisRoute,
  ReposRepoIdIndexRoute: ReposRepoIdIndexRoute,
}

const ReposRepoIdRouteWithChildren = ReposRepoIdRoute._addFileChildren(
  ReposRepoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  SettingsRoute: SettingsRoute,
  ReposRepoIdRoute: ReposRepoIdRouteWithChildren,
  ReposIndexRoute: ReposIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
